# Generated by Django 3.2.5 on 2021-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPeresep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peresep', models.CharField(help_text='Input nama peresep', max_length=30, verbose_name='Nama Peresep')),
            ],
            options={
                'verbose_name_plural': 'Data DataPeresep',
            },
        ),
    ]
