# Generated by Django 3.2.5 on 2021-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakunjungan',
            name='file_up',
            field=models.FileField(blank=True, upload_to='docs/%Y/%m/%d'),
        ),
    ]
