# Generated by Django 3.2.5 on 2021-07-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0005_delete_datadokter'),
        ('poli', '0002_auto_20210727_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_kunjungan', models.DateField()),
                ('no_resep', models.PositiveSmallIntegerField()),
                ('diagnosa', models.ManyToManyField(to='poli.Diagnosa')),
                ('nama_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.datapasien')),
                ('penulis_resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poli.dataperesep')),
            ],
        ),
    ]
