# Generated by Django 3.2.5 on 2021-07-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poli', '0003_datakunjungan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datakunjungan',
            options={'verbose_name_plural': 'Data Kunjungan Pasien'},
        ),
    ]
