# Generated by Django 3.2.5 on 2021-07-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_auto_20210727_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataDokter',
        ),
    ]
