# Generated by Django 3.2.5 on 2021-07-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(help_text='Tulis nama obat dan dosisnya', max_length=100)),
                ('satuan', models.CharField(choices=[('TAB', 'Tablet'), ('SYR', 'Sirup'), ('CAP', 'Kapsul'), ('BKS', 'Bungkus'), ('SAL', 'Salep'), ('CRM', 'Krim'), ('PCS', 'Pcs'), ('BTL', 'Botol'), ('SET', 'Set'), ('KTK', 'Kotak')], help_text='Bentuk sediaan', max_length=3, verbose_name='Bentuk sediaan')),
                ('ab', models.BooleanField(help_text='Check jika termasuk antibiotik', verbose_name='Antibiotik?')),
                ('okt', models.BooleanField(help_text='Check jika termasuk narko/psiko', verbose_name='Narkotik / Psikotropik')),
                ('is_alkes', models.BooleanField(help_text='Check jika bukan obat konsumsi / alkes', verbose_name='Alkes?')),
            ],
            options={
                'verbose_name_plural': 'Data Obat',
            },
        ),
        migrations.CreateModel(
            name='StokObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml', models.SmallIntegerField(verbose_name='Jumlah')),
                ('tgl_kadaluarsa', models.DateField(verbose_name='Tanggal Kadaluarsa')),
                ('nama_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.dataobat')),
            ],
            options={
                'verbose_name_plural': 'Stok Obat',
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveSmallIntegerField(verbose_name='Jumlah')),
                ('aturan_pakai', models.PositiveSmallIntegerField(choices=[(0, '3x1'), (1, '2x1'), (2, '1x1'), (3, 'sue'), (4, 'sprn'), (5, 'suc')], verbose_name='Aturan Pakai')),
                ('lama_pengobatan', models.PositiveSmallIntegerField(verbose_name='Lama Pengobatan (hari)')),
                ('kunjungan_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poli.datakunjungan')),
                ('nama_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.stokobat')),
            ],
            options={
                'verbose_name_plural': 'Resep',
            },
        ),
    ]
