# Generated by Django 3.2.5 on 2024-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOApotek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField()),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Stok Opname Apotek',
            },
        ),
    ]
