# Generated by Django 3.2.5 on 2021-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='prev_saldo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
