# Generated by Django 3.2.5 on 2021-08-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0002_resep_prev_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='after_pengurangan_saldo',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='resep',
            name='prev_saldo',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
