# Generated by Django 3.2.5 on 2024-02-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0003_sogudang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soapotek',
            options={'verbose_name_plural': 'SO Apotek'},
        ),
        migrations.AlterModelOptions(
            name='sogudang',
            options={'verbose_name_plural': 'SO Gudang'},
        ),
    ]
