# Generated by Django 3.2.5 on 2021-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0003_auto_20210727_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Out',
            new_name='Resep',
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='StokObat',
        ),
        migrations.AlterModelOptions(
            name='stokobat',
            options={'verbose_name_plural': 'Stok Obat'},
        ),
    ]
