# Generated by Django 3.2.5 on 2021-08-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0003_auto_20210803_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_terima', models.DateField(verbose_name='Tanggal Terima')),
                ('notes', models.TextField(blank=True)),
                ('file_up', models.FileField(blank=True, upload_to='docs/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='SumberTerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveSmallIntegerField(verbose_name='Jumlah')),
                ('tgl_kadaluarsa', models.DateField(blank=True, null=True)),
                ('prev_saldo', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('after_pengurangan_saldo', models.SmallIntegerField(default=0, editable=False)),
                ('nama_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.dataobat')),
                ('terima_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.bukupenerimaan')),
            ],
        ),
        migrations.AddField(
            model_name='bukupenerimaan',
            name='sumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.sumberterima'),
        ),
    ]
