# Generated by Django 3.2.5 on 2021-07-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0004_auto_20210727_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resep',
            options={'verbose_name_plural': 'Resep'},
        ),
    ]
