# Generated by Django 3.2.5 on 2021-10-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0005_auto_20210804_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobat',
            name='is_jkn',
            field=models.BooleanField(default=False, help_text='Check jika obat beli dari dana JKN', verbose_name='Obat beli dari dana JKN?'),
            preserve_default=False,
        ),
    ]
