# Generated by Django 3.2.5 on 2021-07-27 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0005_alter_resep_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobat',
            name='is_alkes',
            field=models.BooleanField(default=0, help_text='Check jika bukan obat konsumsi / alkes', verbose_name='Alkes?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resep',
            name='aturan_pakai',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '3x1'), (1, '2x1'), (2, '1x1'), (3, 'sue'), (4, 'sprn'), (5, 'suc')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resep',
            name='lama_pengobatan',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stokobat',
            name='tgl_kadaluarsa',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stokobat',
            name='jml',
            field=models.SmallIntegerField(),
        ),
    ]
