# Generated by Django 3.2.5 on 2021-11-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0006_dataobat_is_jkn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StokObat',
            new_name='StokObatGudang',
        ),
    ]
