# Generated by Django 3.2.5 on 2021-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0006_auto_20210727_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='aturan_pakai',
            field=models.PositiveSmallIntegerField(choices=[(0, '3x1'), (1, '2x1'), (2, '1x1'), (3, 'sue'), (4, 'sprn'), (5, 'suc')], verbose_name='Aturan Pakai'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='jumlah',
            field=models.PositiveSmallIntegerField(verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='lama_pengobatan',
            field=models.PositiveSmallIntegerField(verbose_name='Lama Pengobatan (hari)'),
        ),
        migrations.AlterField(
            model_name='stokobat',
            name='jml',
            field=models.SmallIntegerField(verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='stokobat',
            name='tgl_kadaluarsa',
            field=models.DateField(blank=True, verbose_name='Tanggal Kadaluarsa'),
        ),
    ]
