# Generated by Django 3.2.5 on 2021-07-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poli', '0004_alter_datakunjungan_options'),
        ('apotek', '0007_auto_20210727_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='kunjungan_pasien',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poli.datakunjungan'),
            preserve_default=False,
        ),
    ]
