# Generated by Django 3.2.5 on 2021-11-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0007_rename_stokobat_stokobatgudang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stokobatgudang',
            options={'verbose_name_plural': 'Stok Obat Gudang'},
        ),
        migrations.RenameField(
            model_name='dataobat',
            old_name='ab',
            new_name='is_ab',
        ),
        migrations.RenameField(
            model_name='dataobat',
            old_name='okt',
            new_name='is_okt',
        ),
        migrations.AddField(
            model_name='dataobat',
            name='is_non_generik',
            field=models.BooleanField(default=False, help_text='Check jika termasuk obat non generik', verbose_name='Non Generik?'),
            preserve_default=False,
        ),
    ]
