# Generated by Django 3.2.5 on 2021-11-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0009_auto_20211104_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuPengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_keluar', models.DateField(verbose_name='Tanggal Keluar')),
                ('notes', models.TextField(blank=True)),
                ('file_up', models.FileField(blank=True, upload_to='docs/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Buku Terima Gudang',
            },
        ),
        migrations.CreateModel(
            name='TujuanKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tujuan Keluar',
            },
        ),
        migrations.AlterModelOptions(
            name='bukupenerimaan',
            options={'verbose_name_plural': 'Buku Terima Gudang'},
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveSmallIntegerField(verbose_name='Jumlah')),
                ('prev_saldo', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('after_pengurangan_saldo', models.SmallIntegerField(default=0, editable=False)),
                ('keluar_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.bukupengeluaran')),
                ('nama_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.dataobat')),
            ],
        ),
        migrations.AddField(
            model_name='bukupengeluaran',
            name='sumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.tujuankeluar'),
        ),
    ]
