# Generated by Django 3.2.5 on 2021-11-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0011_auto_20211104_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penerimaan',
            options={'verbose_name_plural': 'Item Penerimaan'},
        ),
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'verbose_name_plural': 'Item Keluar'},
        ),
        migrations.AlterField(
            model_name='dataobat',
            name='is_jkn',
            field=models.BooleanField(help_text='Check jika obat beli dari dana JKN', verbose_name='Dari dana JKN?'),
        ),
        migrations.AlterField(
            model_name='pengeluaran',
            name='nama_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apotek.stokobatgudang'),
        ),
    ]
